### ISSUE TITLE
Ability to select from multiple monitors

### ISSUE THREAD

**Issue by sereby** [blackholeearth/Win10_BrightnessSlider#10]
This is a request to add the ability to select which monitor the slider affects. If a user has multiple monitors, perhaps each could be represented as a tab or button with a number label (1, 2, etc.); the user would click on the number of the monitor to adjust its brightness. Shift-clicking on numbers would select multiple monitors to adjust at the same time.

**Comment by blackholeearth** [comment]
all monitors have  seperate sliders
