### ISSUE TITLE
UI stuff

### ISSUE THREAD

**Issue by iJahangard** [blackholeearth/Win10_BrightnessSlider#103]
The app is so simple and lightweight, so that is why i use it

But there is problems with the UI
1. Not compatible with light mode of windows 10 , in tray icon color and the app's windows
2. App and brightness icons are argh, in my opinion you should try some new icons (not a big deal for just two icons haha)
3. Slider UI is so so much bad, it needs a lighter line with different color , and that rectangle on the line to be simply a circle
4. THERE IS NO ANIMATIONS AT ALL 
5. Using a Blur background can be so nice!

**Comment by blackholeearth** [comment]
1 2 3 is done at latest version
