### ISSUE TITLE
Build 17107 Bug

### ISSUE THREAD

**Issue by veawho** [blackholeearth/Win10_BrightnessSlider#11]
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.Management.ManagementException: 不支持 
   在 System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   在 System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   在 Win10_BrightnessSlider.Form1.GetBrightness()
   在 Win10_BrightnessSlider.Form1.UpdateStatesOnGuiControls()
   在 Win10_BrightnessSlider.Form1.Form1_Load(Object sender, EventArgs e)
   在 System.Windows.Forms.Form.OnLoad(EventArgs e)
   在 System.Windows.Forms.Form.OnCreateControl()
   在 System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   在 System.Windows.Forms.Control.CreateControl()
   在 System.Windows.Forms.Control.WmShowWindow(Message& m)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   在 System.Windows.Forms.Form.WmShowWindow(Message& m)
   在 System.Windows.Forms.Form.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

 **trimmed error log**

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

**Comment by blackholeearth** [comment]
duplicate of https://github.com/blackholeearth/Win10_BrightnessSlider/issues/3

**Comment by blackholeearth** [comment]
v 1.02 is released.   it support  ddc/ci  via dxva2   . that means if your monitor supports "ddc/ci", and it is ENABLED in the monitor settings.  
you can try your luck.

**Comment by blackholeearth** [comment]
updated to v1.02   download  new exe , please,
