### ISSUE TITLE
1.7.14 Memory leak

### ISSUE THREAD

**Issue by lynrayy** [blackholeearth/Win10_BrightnessSlider#111]
https://i.imgur.com/urxmshV.png

**Comment by blackholeearth** [comment]
Use 1 previous release.

**Comment by blackholeearth** [comment]
v1.7.15   is released try it. pls . if persist. write here.

if no sound from you in 10 days. i will consider fixed

here:
https://github.com/blackholeearth/Win10_BrightnessSlider/releases
