### ISSUE TITLE
Suggestion : make scroll wheel adjust the slider

### ISSUE THREAD

**Issue by jaylay99** [blackholeearth/Win10_BrightnessSlider#119]
The Windows' sound icon gives us the ability to use scroll wheel to adjust the sound just by hovering your mouse on it. That'd be great if that also worked with W10 Brightness Slider. That's pretty much it, that'd be a great QoL feature.

Thanks!

**Comment by elktelomete** [comment]
It's already possible to adjust with the scroll wheel :)

**Comment by blackholeearth** [comment]
At latest version 

you can hover on tray icon. Scroll will change brightness .

İf iam not wrong it only work for the 1st or single monitor
