### ISSUE TITLE
Getting Trojan alert!

### ISSUE THREAD

**Issue by chippie** [blackholeearth/Win10_BrightnessSlider#12]
I am getting Trojan:Win32/Spursint.F!cl alerts with the latest download. Cannot see this being a false positive! Any other explanations please?

**Comment by blackholeearth** [comment]
1) alert shows up "run only if you trust this app."   if you use debug output of vs2015  in other computer  .
2) decompile into source code and look at it yourself.

**Comment by chippie** [comment]
Thanks, Windows Defender will not even let me download it unfortunately. Did not get this with the initial version.

Greatly appreciate all your hard work!!!!

**Comment by blackholeearth** [comment]
virus total result:
 https://www.virustotal.com/#/file/a6b1a5616f8067f95e17ee74907ccfbdc41f4cc46fa83f8d71ac8d0887a37679/detection

please scan it yourself too.

**Comment by chippie** [comment]
Thank You!

Problem is that both of my laptops refuse to save it, both identify the same trojan :-(

**Comment by chippie** [comment]
There is just NO way that Windows (1709) with the latest Defender updates will let this file even sit on my drives anywhere. It even detects it as a Trojan in my email inbox.

Can you try to rebuild it? There is something in there that is causing this. The previous version did not have this issue.

Thanks!

Mark.

**Comment by blackholeearth** [comment]
a) i submitted file to  microsoft. it said  not a malware.  maybe they update their virus definiton.  if you have update buttun at windefender. try update.

b) disable antivus. put it into ignore list . reaable it.  

î cant go back to previous code sorry.
