### ISSUE TITLE
Suggestion :  adjust screen brightness with keyboard shortcuts

### ISSUE THREAD

**Issue by ntq-cuongpn** [blackholeearth/Win10_BrightnessSlider#120]
Great application! I was able to use it. But if possible, you should integrate with the shortcut of window. for example fn+f1. and please allow to customize it

**Comment by blackholeearth** [comment]
Duplicate.  Pinned to top.
Sesrch before opening issue. 

Fn keys are not catchable by os. İts vendor specific.
Only vendor apps/dll can handle. 
Each pc/laptop/keyboard is different.
