### ISSUE TITLE
Integration into Home Assistant

### ISSUE THREAD

**Issue by DivanX10** [blackholeearth/Win10_BrightnessSlider#122]
Maybe your program has commands for adjusting the brightness through the Windows console, but I didn't find something. If there are such commands, then give some examples for adjusting the brightness through the console on Windows, and if there is no such function, then you could implement commands for this program to adjust the brightness through the Home Assistant. For example, there is such an IO Link integration that monitors the computer and through this program you can run various commands, you can use the same nircmd. This is necessary to automate the control of screen brightness. I'm tired of changing the brightness manually between games, movies and web surfing.  Home Assistant can do all this via IO Link, only I do not know the commands from Win 10_Brightness Slider to adjust the brightness

**Comment by blackholeearth** [comment]
https://github.com/emoacht/Monitorian

this guy has  shortcut and run commandline.

**Comment by DivanX10** [comment]
> https://github.com/emoacht/Monitorian
> 
> this guy has shortcut and run commandline.

Thank you, this is what I need ). I can now change the brightness through the console with this command, well, now my Home Assistant will set the desired brightness for games, for movies and for Internet surfing

%LOCALAPPDATA%\Microsoft\WindowsApps\Monitorian.exe /set 10
%LOCALAPPDATA%\Microsoft\WindowsApps\Monitorian.exe /set 20
%LOCALAPPDATA%\Microsoft\WindowsApps\Monitorian.exe /set 30
%LOCALAPPDATA%\Microsoft\WindowsApps\Monitorian.exe /set 40
