### ISSUE TITLE
Brightness slider goes to -1 and stopped working

### ISSUE THREAD

**Issue by Fmxvxx** [blackholeearth/Win10_BrightnessSlider#123]
Win10 brightness slider stuck on -1 adjusting slider does not change brightness issue occurred on v1.7.14 but downloading v1.7.15 did not solve the issue been using  v1.7.14  on this machine for about a year without issue unsure what has caused this problem 

[logs.txt](https://github.com/blackholeearth/Win10_BrightnessSlider/files/9122075/logs.txt)
![image](https://user-images.githubusercontent.com/109364751/179256170-dea2f180-d40b-4fbd-afc9-dc43e8c62b2e.png)

**Comment by blackholeearth** [comment]
This is not caused by this app  its because windows probably updated , broken something.

Read here: #51
