### ISSUE TITLE
Second monitor can't be controlled by win10_briSlider

### ISSUE THREAD

**Issue by Lotusod** [blackholeearth/Win10_BrightnessSlider#128]
I have 2 monitors but the system is Extend these displays...........

we need different monitors with different controls. is that possible?

**Comment by blackholeearth** [comment]
send me a screenshot  photo of . i dont understand.. 

did you tried to use it ?? what happened ??

**Comment by Lotusod** [comment]
![IMG_20220924_125856.jpg](https://user-images.githubusercontent.com/99648192/192084728-65ef4d38-8b1d-436c-a9e0-f8c061acc36e.jpg)

**Comment by blackholeearth** [comment]
Without extend mode. Does it work?.

**Comment by Lotusod** [comment]
No, not working

**Comment by Lotusod** [comment]
![IMG_20220924_160841.jpg](https://user-images.githubusercontent.com/99648192/192092414-4e9d7cda-42ca-4e4d-a201-770fcf2537fd.jpg)

**Comment by blackholeearth** [comment]
No matter what second monitor brightness cant be controlled by win10_bri_slider.exe right??.

Try emoacht/monitorian 

Similar exe better coding.

**Comment by Lotusod** [comment]
yes, but the second monitor's brightness isn't working...... help please

**Comment by blackholeearth** [comment]
https ://github.com/emoacht/Monitorian  

Download this app.
He is more professional than me.
