### ISSUE TITLE
[Request]  add label/name for the brighness

### ISSUE THREAD

**Issue by binhjy** [blackholeearth/Win10_BrightnessSlider#129]
![image](https://user-images.githubusercontent.com/16265532/201461715-4cfd89e8-d1c7-4c6e-8ba7-c7a9279736d6.png)
I suggest to have a feature to write the name/label so that we can easily to know which one is which? like laptop, screen 1.
Thanks.

**Comment by blackholeearth** [comment]
Done . 

Checkout latest version.
