### ISSUE TITLE
Brightness slider covers taskbar when taskbar is set to auto-hide

### ISSUE THREAD

**Issue by iamFez** [blackholeearth/Win10_BrightnessSlider#130]
### issue

  - [x] fixed:  for only Bottom  and Right .  -  at v1.8.11 
  - [ ] not fixed:  for only Left  and Top. 

----

Hi,

When opening the program to adjust brightness it will open on top of the taskbar. This happens if you have set your taskbar to automatically hide when out of focus in the Windows taskbar settings. 

Windows 10 version 21H2
Brightness Slider version 1.7.15

![image](https://user-images.githubusercontent.com/38197216/202594106-074f3c9b-6b6e-4955-9fa9-ecda28bb68d5.png)

![image](https://user-images.githubusercontent.com/38197216/202594407-92cc4ec9-ed16-4848-99d9-53052d9ef895.png)

**Comment by blackholeearth** [comment]
at v1.8.11 
  * fixed:  for only Bottom  and Right .
