### ISSUE TITLE
VirusTotal show some warnings

### ISSUE THREAD

**Issue by stagira** [blackholeearth/Win10_BrightnessSlider#131]
Hi,

VirusTotal show warnings in the last version (4 warn).

You can see the report there:

https://www.virustotal.com/gui/file/55e4a4b53d6d34e19eb86ba27495b48339b57b573aef79682df86e3f72063c4d

sorry if question was already asked. I think it is closes to the Defender issue.

Can somene explain to me why ? Is there a way to have a clean report ?

Thank you very much. 

Regards 
Philippe

**Comment by blackholeearth** [comment]
#31
