### ISSUE TITLE
[request] Add  win11 look and feel 

### ISSUE THREAD

**Issue by Armaan2311** [blackholeearth/Win10_BrightnessSlider#132]
1) should have **light theme** and **dark theme**. I use Dark theme but the color is black should be grey-blue as in **Windows11** deafult dark theme. 

2) make its UI same as volume control in Win11.

3) make curved corners .

4) change name to Win11_BrightnessSlider

5)  There is already an enchancement submitted for control brightness by hovering mouse over it. Thank you.

**Comment by blackholeearth** [comment]
[v1.7.18](https://github.com/blackholeearth/Win10_BrightnessSlider/releases/tag/v1.7.18)  win11 dark theme
[v1.7.19](https://github.com/blackholeearth/Win10_BrightnessSlider/releases/tag/v1.7.19) dark  + light
