### ISSUE TITLE
[ Request] On/off toggle option for Night Light

### ISSUE THREAD

**Issue by gaveitatry2** [blackholeearth/Win10_BrightnessSlider#133]
I had LASIK eye surgery, and my eyes seem sensitive to the light. So I've been dimming my screens and even started using the Night Light which is where your screen using an amber color light instead of the default blue cool light. Your program helped me so much by letting me easily adjust the brightness settings from the Taskbar.

But anytime I feel like doing something like gaming, I like to turn the Night Life off. And in order to do so on Windows 10, I have to go to the following:
Settings > System > Display > Night Light Settings > Turn Off/On Now

It would be nice if I could access this from your program instead.

![ApplicationFrameHost_CVsfEGAR0X](https://user-images.githubusercontent.com/75463665/209224404-081443c7-e362-411d-8361-4ab0508107bf.png)

**Comment by blackholeearth** [comment]
İts already in  notification center

![notif_center](https://i.stack.imgur.com/d9HMC.png
)

**Comment by gaveitatry2** [comment]
I don't use Notification Center (I have it disabled), that's why I requested the feature for your program.

**Comment by gaveitatry2** [comment]
Nevermind. Even though I have Action Center hidden from the system tray and want to keep it hidden, I can still open it by pressing Start + A.

**Comment by gaveitatry2** [comment]
It's funny, because if I just use the Action Center, I don't need your program. There is a brightness slider in the Action Center.

**Comment by gaveitatry2** [comment]
I would prefer to keep my Action Center hidden, use your program, and have the ability to toggle Night Light off/on using your program. But I can tell you aren't interested. Thank you anyway.

**Comment by blackholeearth** [comment]
yes. there no direct api. 
they change it with every update.  its fragile brittle .

there are hack to trigger with regedit value. its unstable. thats why i dont use it.

i use flux.

**Comment by gaveitatry2** [comment]
Thank you for the information. Do you have a link to the Flux?

**Comment by blackholeearth** [comment]
https://justgetflux.com
