### ISSUE TITLE
there is no exe file to launch it?

### ISSUE THREAD

**Issue by yaron86** [blackholeearth/Win10_BrightnessSlider#134]
hey, i just installed a fresh windows 11, i download it and extract the files, and this is the file structure:
![image](https://user-images.githubusercontent.com/3582979/209424550-453ea63a-8366-4a8c-8ee8-be6501d846fb.png)
there is no exe file... how can i open the program?

**Comment by micbed86** [comment]
Bro! You've missed the right download link: 
![Screenshot2396](https://user-images.githubusercontent.com/121578483/209863899-2882e614-1501-4d75-a74e-9c964d226a64.png)

Click here:
https://github.com/blackholeearth/Win10_BrightnessSlider/releases
