### ISSUE TITLE
Slider constantly overrides settings

### ISSUE THREAD

**Issue by Xarik** [blackholeearth/Win10_BrightnessSlider#135]
At this point, I want it completely off my computer. It overrides its own settings whenever I launch a game or change a window, even if I quit the application/process/service. It isn't even running and my windows brightness is dimmed. If I launch the program again and change the brightness to 100, it becomes way brighter. I quit out of the program and 5 minutes later, it's dim again. Where does it dump its files so I can remove it entirely. I'm guessing in the registry because nothing actually gets installed.

**Comment by blackholeearth** [comment]
Are sure you exit app??

-----
Delete the exe. İts single file.
No setting (json or ini ) is saved. 

----
There is One thing in the registry.
 İt is " run at startup." 
İt show up in  win 10 task manager.

**Comment by Xarik** [comment]
Yes, I kill the program entirely. The existence of the EXE shouldn't make a
difference I wouldn't think, but I'll test that out. The screens will
randomly change from dim to bright when I switch between programs. I've
added a second monitor to my setup and it does it to both now.
