### ISSUE TITLE
Icon tool tip should show current brightness

### ISSUE THREAD

**Issue by CaffeinePwrdAl** [blackholeearth/Win10_BrightnessSlider#14]
Hey there,

When you mouse over the icon the tooltip is just the name of the form component, I've taken a fork of your project and made the change locally that sets the mouse over message to be something nicer and show the current brightness level.

This change on my fork: 87d6b14c4094e3d508bbe80ebf3a2296eb12eedd

Alex

**Comment by blackholeearth** [comment]
exe v1.02 but code is v1.0  so i changed some things. but changes not pushed here.

 ty anway
