### ISSUE TITLE
Is there a way to change the default brightness increments in Win10?

### ISSUE THREAD

**Issue by Alan996** [blackholeearth/Win10_BrightnessSlider#140]
When using my laptop, I have noticed that the Win10 default increments of brightness are 10% when pressing the brightness button. However, this is too big of a step for my laptop. I have searched for ways to change the increments but almost all of them tell me that it is not possible.. -_-! link:[https://answers.microsoft.com/en-us/windows/forum/all/brightness-increments-are-at-10-possible-to-change/2617b9fb-515e-4d87-b898-d0cec0ec4790](https://answers.microsoft.com/en-us/windows/forum/all/brightness-increments-are-at-10-possible-to-change/2617b9fb-515e-4d87-b898-d0cec0ec4790)

**Comment by blackholeearth** [comment]
İ don't know.  ask in microsoft . Windows forums.
