### ISSUE TITLE
[Question] Where are the Win10 Brightness Slider settings stored?

### ISSUE THREAD

**Issue by gaveitatry2** [blackholeearth/Win10_BrightnessSlider#142]
I have had this problem every single day since I installed Win10 Brightness Slider many months ago. When I first used your program, I set the brightness to Level 15 because I had eye surgery and my eyes are sensitive to light. Since then, I have gradually increased the brightness to Level 30 and Level 50.

The problem is that if I open up some programs like a free Steam game called Sven Co-op, the brightness level doesn't change. So if I had it on Level 50, it stays on Level 50 when I open up the game. But if I close Sven Co-op, the brightness level suddenly changes to Level 15 for no reason.

I was thinking that maybe it would help if I found out where the program settings are and delete them and start over. All I have is the exe file. But I can't find the settings folder in Local or Roaming AppData. I can't find it in Registry Editor. Where can I clear the cache at?

**Comment by blackholeearth** [comment]
No cache or settings file, nothing is saved..  
Only thing saved is run at startup.

İ know that . its also happening to me when i use
Rufus usb boot exe. When i open or close the rufus.exe 

Some apps trigger this. 

But İ coudnot find any solution related to this online. 

İs this happened with older version  like v1.4  ??
