### ISSUE TITLE
stopped working after using christitus win tweaks

### ISSUE THREAD

**Issue by DennisKerman** [blackholeearth/Win10_BrightnessSlider#145]
Hello and thx alot for this awesome tool!

I set all processes to manual via the mentioned tool from christitus (win debloat).
I am very sure thats the reason your tool is no longer changing the brightness. I do not know what process to reset. 
Sorry to ask for help, i have been thru all of them but the one you are using i coulndt find..
maybe its a different reason but thats my working theory.

**Comment by DennisKerman** [comment]
whenever i click on the slider now at first it will show -1 for some reason and then any input will result in no change, maybe that helps

**Comment by DennisKerman** [comment]
sry just found the log:
11.05.2023 11:13:00 ==>  Caller(File,Member,Line): RichInfoScreen.cs, Get_RichInfo_Screen, 183 
Exception:
System.Runtime.InteropServices.COMException (0x80070422): Der angegebene Dienst kann nicht gestartet werden. Er ist deaktiviert oder nicht mit aktivierten Geräten verbunden.

   bei System.Management.ThreadDispatch.Start()
   bei System.Management.ManagementScope.Initialize()
   bei System.Management.ManagementObjectSearcher.Initialize()
   bei System.Management.ManagementObjectSearcher.Get()
   bei Win10_BrightnessSlider.wmiMonFn.GetWMIMonitorIDs()
   bei Win10_BrightnessSlider.RichInfoScreen.Get_RichInfo_Screen() 


11.05.2023 11:13:00 ==>  Caller(File,Member,Line): dxvaMonFn.cs, GetPhysicalMonitorBrightness, 153 
System.ComponentModel.Win32Exception (0x80004005): Beim Übertragen der Daten an das Gerät auf dem I2C-Bus ist ein Fehler aufgetreten

**Comment by blackholeearth** [comment]
#51
