### ISSUE TITLE
Window is shown behind 'show hidden icons' tray

### ISSUE THREAD

**Issue by CaffeinePwrdAl** [blackholeearth/Win10_BrightnessSlider#15]
Hey there,

When the tray icon for the app is inside the hidden icons tray, to adjust brightness you pop open the tray, click the icon, but the window appears behind the tray.

Seems BringToFront() isn't quite enough, but if you set TopMost as well it appears to do the trick.

Just add:

```
+                this.TopMost = true;
                 this.Activate();
                 this.Show();
```

to eSetVis().

Should have made smaller commits, but you can see the change in my commit here: 

db9d4dcf72045c98e1a5348ca87a7dcbd25db039

Thanks for writing the app by the way 🥇 

Regards,

Alex

**Comment by blackholeearth** [comment]
code on github is old. ty for help.  that part take half of my day . until i found out. all of em fixed in v1.02 ' code but . not uploaded here. but exe is latest.
