### ISSUE TITLE
exe is seen as virus by windows defender

### ISSUE THREAD

**Issue by Pinox64** [blackholeearth/Win10_BrightnessSlider#156]
Unable to run since I checked "run at startup" and then another option from task tray menu (cant remember which)
![image](https://github.com/user-attachments/assets/e5c57011-1b38-4833-bd34-4b66f1f69469)
![image](https://github.com/user-attachments/assets/e39b7b30-55b9-4545-a394-27e8adb23c91)

**Comment by PacaAlpaca** [comment]
At this moment 4 antivirus engines detect it as a virus which can be a problem.Maybe this is because of using packer? Can you do not use it?

![obraz](https://github.com/user-attachments/assets/9efed187-8b50-453d-b3a2-27baea2d980e)

**Comment by blackholeearth** [comment]
SUBMİTTED HERE:

https://www.microsoft.com/en-us/wdsi/submission/60bb689e-29c3-4e81-91ca-31da309185c3

**Comment by blackholeearth** [comment]
![SCR](https://github.com/user-attachments/assets/216735de-f573-4a81-a0ee-91129dfaba0d)

**Comment by blackholeearth** [comment]
i disabled the  compression of costura.fody. as its dev suggested in github.

this shouldn't give virus alert...  

can you try,  see the defenders reaction.... ??

[Win10_BrightnessSlider_1.8.7_fody-nocompression.zip](https://github.com/user-attachments/files/17543465/Win10_BrightnessSlider_1.8.7_fody-nocompression.zip)

**Comment by PacaAlpaca** [comment]
It is still detected by 2 AV engines (both not from top tier) but when downloaded and started, Windows SmartScreen or Windows Defender doesn't complain (maybe your submit to MS works or this, who knows)

![obraz](https://github.com/user-attachments/assets/974c60ff-7daf-4290-9a27-2d43f193fbaf)
[Link (advanced view only for registered/paid users :/)](https://www.virustotal.com/gui/file/8f9d8f58d43b34e05a20576fa21c9d43bb69b1d3df92c64bbe6de8e5da76f844?nocache=1)

Maybe this is also corelated with using _GetTickCount_ or _IsDebuggerPresent_ which are used sometimes by malware to check if is running in virtual machine or being debugged and then hide any suspicious functions

![obraz](https://github.com/user-attachments/assets/80f357f5-addf-420f-89b5-2ec8046a1a35)
