### ISSUE TITLE
Error running  v1.8.7   (& earlier version)

### ISSUE THREAD

**Issue by kroncke-w** [blackholeearth/Win10_BrightnessSlider#157]
Gets this error message in win 11 24h2 insider pre-release build .26100.2161 with current MS updates.
it then caannot be deleted until reboot or user logoff - logon again. I am running as admin on an AMD Ryzen 5700U system with 32GB ram and a 512gb SSD drive.
![image](https://github.com/user-attachments/assets/d0f387d9-eb44-435b-90e0-0353063aef6f)

**Comment by blackholeearth** [comment]
i searched internet your dot net framework is corrupt... probably all your c# apps throing this error.

try install it again.

https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net481-offline-installer
