### ISSUE TITLE
[Fallback to ddc/ci  mechanism]  Doesn't work

### ISSUE THREAD

**Issue by psydex** [blackholeearth/Win10_BrightnessSlider#16]
![screenshot_2](https://user-images.githubusercontent.com/5594251/38885903-0db4c2f4-427d-11e8-8efb-a28290d480e9.jpg)

Using Win 10 Pro
Version 1709
OS Build 16299.248
GPU: Nvidia GTX650
Monitor: Samsung SyncMaster S22B150

_.NET Framework 4.7.1 or a later update is already installed on this computer._

![screenshot_3](https://user-images.githubusercontent.com/5594251/38886289-32254d24-427e-11e8-8c61-8ac465468088.jpg)

**Comment by blackholeearth** [comment]
hi try new version . i triesd the fix that showed up in that  message    MonFn_getbrighness . 

https://github.com/blackholeearth/Win10_BrightnessSlider/blob/master/Win10_BrightnessSlider/bin/Debug/Win10_BrightnessSlider.exe?raw=true

**Comment by blackholeearth** [comment]
same  with #3 .   but  due to  falback being implemented, this Management Not supported Shoudnt Show up this is bug.

**Comment by psydex** [comment]
v1.04 (Devbug) works! But you have to press _Detect monitor_ first which is inconvenient after each reboot

**Comment by blackholeearth** [comment]
detect monitor is for::  when you plug and unplug new  monitor.  if you dont plug and unplug new monitor . you dont even need to use it.

> Can you make it detect monitor automatically on boot?

 when app start it should detect all monitors . is it  getting monitor ??

**Comment by psydex** [comment]
App works ONLY when I manually press "detect monitor" and doesn't stick after reboot.

**Comment by adamearle** [comment]
I have three screens  everything was working and then I set 1 of my monitor to 100% and it has blown out the monitor to 100% 

it kinda funny cause i cant even use that screen now its just white. hahahaha trying to wotk out how to disable or uninstall it 

hhahaha its kinda funny. love that your work though on this even if messed it did mess up my screen  (partly user error)

thanks bro

ad
