### ISSUE TITLE
Taskbar at top of screen, brightness slider doesn't match

### ISSUE THREAD

**Issue by Wickemu** [blackholeearth/Win10_BrightnessSlider#2]
Any chance that this could be updated so that its position is relative to the taskbar's position? I have my taskbar on top and would love to have this alongside my volume slider, but having it still pop up at the bottom isn't idea.

Great utility, much appreciated!

**Comment by kaartman** [comment]
That's a very good idea. 
I use the task bar at the top, it would be nice to be able to move or you want the tweak with location memorization. 

Anyway, very good work, Tk's.
Regards

**Comment by blackholeearth** [comment]
fixed it

**Comment by Virgus** [comment]
Hello,
I've just found your excellent tool and tested it.
I'm using two toolbars, the top occasionally and the bottom is the default Windows toolbar.

The brightness slider is stuck to the top toolbar when it's active. Please have a look at the Au3Info output about the extra toolbar I'm using here https://imgur.com/a/SpRmCT7
Is there a config file to set some parameters (like preferred position) for the slider bar ?
Thanks again for the tool ! V.
