### ISSUE TITLE
3 Screen

### ISSUE THREAD

**Issue by adamearle** [blackholeearth/Win10_BrightnessSlider#22]
Hey mate so here is where I am at with your work

I have three screens, but I get 5 sliders what,  
1. Computer
2. Cintq
3. TV screen

Just some thoughts here
1. You need a rest button 
2. also perhaps the slider could be named in accordance to the screens

Do you have any idea on how I might be able to reset my screens?

![screenshot_1](https://user-images.githubusercontent.com/16330340/43515430-d6f1899a-95c5-11e8-8c73-8a15bc02b887.png)

**Comment by blackholeearth** [comment]
right click rescan monitorss icon..  maybe helps

i have to debug on that machine . whatever i say here is meaningless

**Comment by adamearle** [comment]
Detect didn't work 
I am wondering if you have seen Pango Bright I'm  kinda hope you can top it
If you want to do some debugging on machine i am happy for that? Let me  know how.

Its permanently dark now it won't go above 38 

Link: https://www.pangobright.com/

**Comment by adamearle** [comment]
Hey bro I am going to be doing a  reinstall of the OS over the weekend, so if you wanted to go for a deep dive and remote into my system to take a look at what might be going on with your code your more than welcome.

Let us know

Ad

**Comment by blackholeearth** [comment]
new version released test it....
