### ISSUE TITLE
 text is not crytal clear (blurry , blocky at high dpi)

### ISSUE THREAD

**Issue by wowns106** [blackholeearth/Win10_BrightnessSlider#24]
The functionality is flawless but it would be much more seamless and blend in better with the Windows UI if it matches the dpi that the OS is running on. I own a Surface Book, a 3000 x 2000 pixel display, which makes the low dpi of this software stand out.

**Comment by blackholeearth** [comment]
post a screen shot please so i can understand better

**Comment by wowns106** [comment]
Here is a rough comparison. On the left is the brightness slider, and on the right is the battery information, running at appropriate dpi. You'll be able to notice the difference in comp1.png, where two images are zoomed in at 3.0x.
![comp1](https://user-images.githubusercontent.com/32991726/44753362-9f768980-aad2-11e8-84cf-faf95decef5f.png)
![comp2](https://user-images.githubusercontent.com/32991726/44753363-9f768980-aad2-11e8-8b8f-80e5ff9cb958.png)

**Comment by blackholeearth** [comment]
i dont want this send me the volume slider . my app aims to match "volume slider."   type

**Comment by wowns106** [comment]
I understand. I'm assuming that you're running at 1920x1080, because the volume slider in fact does not match with the volume slider at 3000x2000. Here are comparison photos below. Again, notice the difference in DPI when zoomed in. The volume slider is clearly more dense in pixels and is running at a higher DPI.

![comp3](https://user-images.githubusercontent.com/32991726/44774105-176e9f00-ab27-11e8-864a-5cde7b3f6518.png)

![comp4](https://user-images.githubusercontent.com/32991726/44774109-1a698f80-ab27-11e8-8645-87cf2dd6831f.png)

![comp5](https://user-images.githubusercontent.com/32991726/44774314-af6c8880-ab27-11e8-86e7-d02d606a7d5d.png)

**Comment by blackholeearth** [comment]
ok  irelease new version  download  v1.7   https://github.com/blackholeearth/Win10_BrightnessSlider/releases  

please  feed back if its showing text crystall clear

**Comment by wowns106** [comment]
The new release does run at higher DPI. Thank you for the quick response! Appreciate your work immensely.
