### ISSUE TITLE
Exception at Getbrighness   

### ISSUE THREAD

**Issue by ffuser1** [blackholeearth/Win10_BrightnessSlider#25]
Updated to newest version and now I have this error... Program still starts but I cannot bring up the brightness slider
![new bitmap image](https://user-images.githubusercontent.com/42816218/44807981-305b6c80-ab88-11e8-8094-b9d9db25c8c1.jpg)

**Comment by blackholeearth** [comment]
https://github.com/blackholeearth/Win10_BrightnessSlider/releases   check 1.7.3
