### ISSUE TITLE
Download Page Blocked by BitDefender Gen:Heur.MSIL.Krypt.4 Trojan

### ISSUE THREAD

**Issue by Pixel-Labs** [blackholeearth/Win10_BrightnessSlider#27]
I can't think of anywhere else to put this, but the download page is blocked by BitDefender:
The page you are trying to access contains Gen:Heur.MSIL.Krypt.4.

It is the Windows 10 Download Link: Win10_BrightnessSlider.exe

VirusTotal shows no problems.

**Comment by blackholeearth** [comment]
disable bit defender. or addon ?? if you dont  trust, dont run.  what can i do .?

there used to be fake alert for win defender . i submitted there now  there are no complaint about it.

similar to #13
