### ISSUE TITLE
Microsoft .Net error while using only a second monitor

### ISSUE THREAD

**Issue by BearWithProject** [blackholeearth/Win10_BrightnessSlider#28]
This error shows up when my laptop is connected to a second monitor and the laptop monitor is turned off. If I select continue nothing is visible. (Version 1.7.4)
This error disappear in version 1.4.0

Error:

Le informazioni su come richiamare il debug JIT (Just-In-Time) anziché questa finestra
sono riportate in fondo al messaggio.

************** Testo dell'eccezione **************
System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
   in Win10_BrightnessSlider.RichInfoScreen.get_PhysicalMonitor()
   in Win10_BrightnessSlider.RichInfoScreen.GetBrightness()
   in Win10_BrightnessSlider.uc_brSlider.UpdateSliderControl()
   in Win10_BrightnessSlider.Form1.UpdateAllSliderControls()
   in Win10_BrightnessSlider.Form1.UpdateStatesOnGuiControls()
   in Win10_BrightnessSlider.Form1.Form1_Load(Object sender, EventArgs e)

<img width="192" alt="error" src="https://user-images.githubusercontent.com/16397940/45168771-6047e700-b1fc-11e8-9150-2d00cdebdca6.png">

**Comment by blackholeearth** [comment]
okey you stay on 1.4.   errod disapeears but does your slider works at 1.4

**Comment by BearWithProject** [comment]
If I use 2 monitor there are 3 sliders, but they work (two of them)

**Comment by blackholeearth** [comment]
https://github.com/blackholeearth/Win10_BrightnessSlider/releases/tag/v1.7.5  try this

**Comment by BearWithProject** [comment]
Now it works!  It shows two sliders correctly but one doesn't work (external monitor). I think it's a monitor problem. I tested the 1.4 version with an LG uhd external monitor and it worked, now the 1.7.5 with an old Benq I can't change the brightness, but as I said, I think it's a monitor problem.
(Now I can't test 1.7.5 on LG monitor)

**Comment by blackholeearth** [comment]
2) if slider working. but suddenly (you plug/unplug monitor/MirrorScreen in any way) then screen act up weird for second.
 you CAN get error while trying to change birghtness, you gotta press "Detect monitor".

**Comment by BearWithProject** [comment]
I pressed "Detect monitor" but it didn't work. I'll try the LG monitor to see if it works.
Thanks for your help!

**Comment by blackholeearth** [comment]
hıım. thats too bad. its unhelping to compare different monittor. 
can you test both 1.4  - 1.7.5 at   benq(or whatever you got) monitor. both version fails ??

**Comment by BearWithProject** [comment]
Both versions fails. If I select "Detect monitor"one slider goes to -1 but the other works

**Comment by blackholeearth** [comment]
okey thats good  if  both  v1.4 v1.7.5 cant control that monitor, its ok at my side.   

thanks for the truoble.
