### ISSUE TITLE
ManagementException: Not supported  Win 10 Build 17046 

### ISSUE THREAD

**Issue by JFMSkis** [blackholeearth/Win10_BrightnessSlider#3]
I handled Exception - see attached image
![image](https://user-images.githubusercontent.com/34242421/33558976-60de99f4-d8d9-11e7-8db1-75124e55e1f1.png)

**Comment by kaartman** [comment]
Hello, i just installed it on Windows10 insider v1709 build17046 and everything works fine.

**Comment by itsakt** [comment]
Same issue. Looks like `WmiMonitorBrightnessMethods` does not work on all systems.

**Comment by blackholeearth** [comment]
@JFMSkis
verify  if you can  change  brightness from windows action center toggle  [0 25 50 100] ? 
does toggle works?

if no :  
my app can't  change brighness if your windows action center toggle doesnt work. 
so what you can do?? you need to install ati/nvdia/intel driver that corresponds to your GraphicCard.

if yes :  
so my app has bug.  
i dont have win10 ver 1709. so i wont be able to test.

@itsakt  yes my app depens on `WmiMonitorBrightnessMethods`

**Comment by kaartman** [comment]
Hello, the graphics card is up to date and i'm running as an administrator. 
Always the same error for windows 10 home 16299.
But no problem on my SP4 in win10 pro insider. 
The home version is different from the pro, the problem may be this.

**Comment by blackholeearth** [comment]
hi
ive seached over the internet heres the result:
https://www.codeproject.com/Questions/459890/WmiSetBrightness-method-not-supported-Net-Winf

i use `WmiSetBrightness `  in my app
it says your graphic card  driver has to have WMİ support.  a way to communicate with windows.
and manufacturer dont have to add  wmi support.  

so its high probable that its related to graphic  driver .  win 10 versions probably is not much of a problem.

**Comment by Azhe403** [comment]
maybe you must install or update driver vga.
Brightness slider maybe only work most Laptop, Notebook or Nebook, not in Desktop PC

**Comment by blackholeearth** [comment]
@JFMSkis  , @kaartman  try the new exe, ive added ddc/ci support v1.02, also can change each monitor brightness seperately, multiple monitor support.

**Comment by blackholeearth** [comment]
fixed at v1.04  .    reported  in here #16  but currently  requires  **right click >detect monitors**  .

**Comment by Jonatino** [comment]
@blackholeearth your app works fine if I run the exe but when I try to run it from source I get this error. Any solution?

**Comment by blackholeearth** [comment]
@Jonatino  because. read me. Been asked least 30times

**Comment by Jonatino** [comment]
@blackholeearth this thread doesn't make any sense. The only explanation is that your graphics card doesn't support it. Which doesn't make sense because why would the released exe work but not the source?

**Comment by blackholeearth** [comment]
Sorce code is  v1.1 .

 exe is v1.79.  

 code is not released.  Only thevfirst  version code is released
