### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Musttodo9t** [blackholeearth/Win10_BrightnessSlider#30]
Can you fix the icon, because it not symmetrical.

**Comment by Musttodo9t** [comment]
and add the percent scale near the icon.

**Comment by Musttodo9t** [comment]
And one more. Can you change the big green ugly icon in batterybar program to windows style and add the percent near the icon.

**Comment by Musttodo9t** [comment]
Thank you for your program its very usefull.

**Comment by blackholeearth** [comment]
> Can you fix the icon, because it not symmetrical.  
invalid

> and add the percent near the icon. 
invalid :  speaker doesnt have % icon.
