### ISSUE TITLE
doesn't do anything

### ISSUE THREAD

**Issue by HenryVMorgan** [blackholeearth/Win10_BrightnessSlider#32]
Tried moving the slider on my pc and nothing happens

**Comment by blackholeearth** [comment]
it doesnt work on all pc's.  

 if it shows up *generic  microsoft  pnp monitor*, you definitely  try to install monitor / graphic drivers both.
 i updated drivers  on my old 2006 pc  with  **driver_booster_setup**.
( it felt like a fake app. but it worked.)
delete updater later if it bothers you mind

**Comment by blackholeearth** [comment]
Also try sunicon >rightclick >detect monitor . There is slight chance it may work.

**Comment by jefken153** [comment]
problem solved
bad drivers on monitor
after deleted the drivers problem was somved
