### ISSUE TITLE
RTL small problem

### ISSUE THREAD

**Issue by ZaFaR97** [blackholeearth/Win10_BrightnessSlider#33]
Thank you, great app.
I have small notice, you can see below, In RTL: the slider appeared in the other side.
if you can make it able to apear in side depend on RTL-LTR, will be Nice.

![image](https://user-images.githubusercontent.com/13044444/49308535-9d650200-f4e9-11e8-93ec-c7e3058e71b6.png)

**Comment by blackholeearth** [comment]
Will check it starting week.
