### ISSUE TITLE
Auto detect when starts

### ISSUE THREAD

**Issue by ZaFaR97** [blackholeearth/Win10_BrightnessSlider#34]
Hi, After restart, I should do detect monitors.
is there any option to make it auto?

Acer G247HYU - 2K
Use last update 1.7.5 | Run At startup ✔️

**Comment by blackholeearth** [comment]
İt should work without you require pressing "detect monitor"". 
 Doesnt it??? Work

**Comment by ZaFaR97** [comment]
Thank you, I test it now, it works!
May be at last time i checked doesn't worked because i run two ver. in One time.
sorry.
