### ISSUE TITLE
Second monitor not active, but brightness slider exists and is set to "-1"

### ISSUE THREAD

**Issue by dominique-mueller** [blackholeearth/Win10_BrightnessSlider#35]
### Details

I own two identical monitors, manufactured by Dell. Both monitors are always connected to my desktop PC, both via a dedicated NVIDIA GPU, one via HDMI and the other one via DP.

At times - such as when gaming - I don't require both monitors to be active. Thus, I tend to configure Windows to only use my main monitor (via "WIN+P", first option). In this case, both Windows and the NVIDIA driver correctly identify only one monitor - and also allow configuration for this one monitor.

### Current behaviour

If only one of two monitors is actually being used by Windows, brightness sliders continue to exist for both monitors. The brightless slider for the "unused monitor" is set to "-1", and the application crashes once I try to change its value. See the screenshot:

![screenshot](https://user-images.githubusercontent.com/7271961/50060053-f641c500-018e-11e9-94eb-e5a29deb7609.jpg)

Running "Detect monitors" does not change this situation. I'm assuming that the brightness slider application somehow still knows about both monitors, probably because I explicitely installed Dell Monitor Drivers for both of them. Both monitors are also always visibile in the Windows device manager.

### Expected behaviour

I would expected the brightness slider for the "unused monitor" to simply not be visible, or disabled ("greyed out").

### Note

This issue doesn't affect the functionality of this application in any kind of critical way. Still, it's confusing to users, and an solving this issue could improve UX quite a bit.

**Comment by blackholeearth** [comment]
"if you/plug/unplug"  device is gone or added.
 mirroring situation is . its plugged but connection is gone. different case.
 i used to have access to external monitors . unfortunately ,right now i dont .  so i cant debug.

maybe in a month or two i ll come back here.

**Comment by PrometheusDan** [comment]
I also have this problem where it says -1, and it won't let me change the brightness at all. How do I fix it?

**Comment by sohateq** [comment]
This issue + second slider of active dispalys doesnot changes brightnes, as long as inactive dispaly is unglugged

**Comment by blackholeearth** [comment]
try v1.7.11 . whats the result ??

**Comment by sohateq** [comment]
> try v1.7.11 . whats the result ??

Hello! I've tried 1.7.14 but problem was not solved
