### ISSUE TITLE
1.7.5 release doesn't work from source

### ISSUE THREAD

**Issue by timotree** [blackholeearth/Win10_BrightnessSlider#36]
The pre-compiled executable works just fine but when I try to run from source I get the same error as #3. I tried executing the PowerShell script from #7 but I get the same "Not Supported" error for WmiMonitorBrightness as I do when I run from source.

**Comment by blackholeearth** [comment]
source is v.1.1  wmi  
exe      is 1.7.5  wmi+dxva

i wont give code here:. 
 i write at main page about this.
