### ISSUE TITLE
Suggestion for taskbar icon, I am running v1.75

### ISSUE THREAD

**Issue by Murielkai** [blackholeearth/Win10_BrightnessSlider#37]
I am running v 1.75 and I'm not sure if this is how the app is meant to run or not but I have to click on my desktop or taskbar to make the slider disappear. A second click on the "sun" icon only makes the slider re-appear rather than making it go away. It would be great if a second click dispelled the slider. Otherwise I love this app, had no issues with it at all.

**Comment by blackholeearth** [comment]
fixed. will release in a week.
