### ISSUE TITLE
slider waits until draggingEnd To Change brightness [on ddci monitors]

### ISSUE THREAD

**Issue by F4CIO** [blackholeearth/Win10_BrightnessSlider#40]
Trivial issue but motivated me to open your source code just to realize its not latest version:)

For primary screen when I drag slider without releasing mouse brightness is immediately updated but for second screen brightness is updated only after mouse button is released. Is this by design and is there any way you can make second slider to work as first? (I have asus screen attached to USB port as second screen to laptop and no option currently to try another device)

Nice tool by the way.

**Comment by SonicGold** [comment]
I'm also having this issue, what can we do to help ?

**Comment by blackholeearth** [comment]
@F4CIO  
1) as i already stated. in the read me.  soruc code is not new.
2) 
 wmi  capable monitors. works  while dragging.
 ddci monitors (as fallback, last resort)  works After drag completed.  i made that  on purpose.
 
why?
 on my ddci monior . if i sent every change to monitor . it freezes computer.  some monitor cant handle too much frequent set brighness  action.

**Comment by F4CIO** [comment]
you can try letting update happens every sec:


private static DateTime lastChange=0;

in event:

if(lastChange.Second!=DateTime.Now.Second){
 lastChange=DateTime.Now;
 //do update...
}

But never mind, its minor issue. 

On February 13, 2019 3:05:08 PM GMT+07:00, blackholeearth <notifications@github.com> wrote:
>@F4CIO  
>1) as i already stated. in the read me.  soruc code is not new.
>2) 
> wmi  capable monitors. works  while dragging.
>ddci monitors (as fallback, last resort)  works After drag completed. 
>i made that  on purpose.
> 
>why?
>on my ddci monior . if i sent every change to monitor . it freezes
>computer.  some monitor cant handle too much frequent set brighness 
>action.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/blackholeearth/Win10_BrightnessSlider/issues/40#issuecomment-463098614

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by blackholeearth** [comment]
thanks i might do this.  in upcoming weeks
