### ISSUE TITLE
Is Detect Monitors really neccessary?

### ISSUE THREAD

**Issue by F4CIO** [blackholeearth/Win10_BrightnessSlider#42]
whatever you do on Detect Monitors you can put it in beginning of OnShow... or OnDraw... event (event that you use to draw sliders) or even OnMouseClick event of icon.

**Comment by F4CIO** [comment]
did you try https://docs.microsoft.com/en-us/dotnet/api/microsoft.win32.systemevents.displaysettingschanged?view=netframework-4.7.2

as alternative you can make timer fire every 5s and compare System.Windows.Forms.SystemInformation.MonitorCount

**Comment by blackholeearth** [comment]
its not vital/necessary right now. maybe in future thank you.
