### ISSUE TITLE
would like to contribute

### ISSUE THREAD

**Issue by CSADn** [blackholeearth/Win10_BrightnessSlider#43]
Hi, I would like to contribute adding keys shorcuts functionality.
I don't want to be credited or anything like that.
My intention is just to contribute adding that feature and nothing else, your app works great and I don't want to start another one from scratch.

Let me know if you are interested.

Best regards,
Adrián.

**Comment by blackholeearth** [comment]
Ok . Send extremly simple code . İf i understand ill add it.   Thx.
