### ISSUE TITLE
Doesn't work with DVI-D VGA converter

### ISSUE THREAD

**Issue by anonym24** [blackholeearth/Win10_BrightnessSlider#47]
My monitor have only VGA 
On previous PC all DDC/CI programs to control brightness was working ok

But now I need DVI-D or HDMI to be able connect my monitor

So I bought next converter, monitor works ok, but brightness programs (including this one) stopped working

![1062424_v01_b](https://user-images.githubusercontent.com/8851301/54492868-d9727600-48d2-11e9-9db3-3892accd93f2.jpg)

**Comment by blackholeearth** [comment]
try 
clickmonitorddc: 
https://www.clickmonitorddc.bplaced.net/
monitorian:
https://github.com/emoacht/Monitorian

if all fails . 
then there is no solution.

**Comment by anonym24** [comment]
@blackholeearth didn't work with them
