### ISSUE TITLE
When switching monitor off and on, settings lost

### ISSUE THREAD

**Issue by domusW** [blackholeearth/Win10_BrightnessSlider#49]
When I set a brightness of, for instance, 54, then switch the monitor off and back on, the brightness is set to 12. Same happens when monitor goes into sleep mode and wakes back up.

**Comment by danarnold** [comment]
This is covered in #68.

However, @blackholeearth, I think it would be awesome if there was an option to automatically run detect monitors at a regular interval. Maybe every 10 seconds or so. For me, I lock my screen often and it times out quite a bit, which means clicking Detect Monitors a dozen or more times per day.

**Comment by Melkster** [comment]
I personally think it would make most sense if the program re-ran "Detect monitors" whenever I activate it, i.e. when I click it to show the sliders. Is there any reason why it doesn't do this right now?

**Comment by blackholeearth** [comment]
try new version  v1.7.11
monitor on off 
monitor plug unplug
system suspend resume events are added

**Comment by blackholeearth** [comment]
detect monitor takes time 2 - 5 seconds.(not sure on exact value).  it is annoying to wait.

**Comment by danarnold** [comment]
1.7.11 is working great for me! I haven't had to Detect Monitors once since installing and I've had many power off events.

**Comment by domusW** [comment]
Installed and tested 1.7.11. Same problem. Switching monitor off and on loses my brightness setting.

**Comment by blackholeearth** [comment]
not just text near slider but your monitors actual brightness lightning ??..   

hardware setting doesnt persist. also i dont do anyting special to keep/save levels of brightness levels.

in this links . its talking about  your monit can be in text Mode. or webPic mode. do you have anyting like that??
if so you have to set it to TextMode to keep/persist settings by hardware
 https://www.tenforums.com/drivers-hardware/101478-external-monitor-brightness-resets-when-turned-off.html

**Comment by domusW** [comment]
Yes, the actual brightness is reset to the internal settings of the monitor. If I change the brightness settings on the monitor, they persist between switching off and on, of course.

When I change the brightness setting in BrightnessSlider, it does not persist between switching the monitor off and on. For instance, if the monitor's internal value is 50 and I open BrightnessSlider and set it to 100, the actual brightness is indeed maximum and the slider shows 100. All fine. When I switch the monitor off and back on, the brightness is back to 50. When I open BrightnessSlider, it also shows 50 (and not 100).

The internal brightness settings of the monitor do persist without problems.

**Comment by blackholeearth** [comment]
if you try windows 10 brightness toggle (0 - 25 -75- 100) . does it persist.

**Comment by blackholeearth** [comment]
SaveCurrentMonitorSettings function (highlevelmonitorconfigurationapi.h)

Saves the current monitor settings to the display's nonvolatile storage.

C++

_BOOL SaveCurrentMonitorSettings(
  HANDLE hMonitor
);

----------------

i found something . ill come back here tomorrow.

**Comment by domusW** [comment]
In the mean time, I have looked for the brightness slider or toggle in Windows 10, but it does not appear on my system. If I recall correctly, that is why I downloaded your solution in the first place, because it did allow me to change brightness without touching the monitor without problems. There just wasn't any persistence.

In any case, thank you very much for putting time in this!

**Comment by blackholeearth** [comment]
https://github.com/blackholeearth/Win10_BrightnessSlider/files/6661356/Win10_BrightnessSlider.zip

try this.??
i added savemonitorsetting.  its only appicable dxva(external plugged cable monitors).

**Comment by domusW** [comment]
It didn't change anything. Monitor is plugged via DVI cable.

I appreciate very much that you put time in this, but if it's just me who's having this issue, you shouldn't waste time on me.

I was thinking, however, what if you just send the brightness command every minute...?

**Comment by blackholeearth** [comment]
what is in tle app logs . are there any errors??.. ( trayicon> rightclick > log)

--------------------------------
i can keep "lastSuccesful setBrightness value _byUser" inside while app is running. 

update when suspend resume/ monitor on off event happens.

**Comment by domusW** [comment]
That would be perfect!

**Comment by blackholeearth** [comment]
i backup restore values between events. i hope this one works

[Win10_BrightnessSlider.zip](https://github.com/blackholeearth/Win10_BrightnessSlider/files/6676946/Win10_BrightnessSlider.zip)

**Comment by domusW** [comment]
It doesn't. :( 

What if you just send the brightness command every minute...?

**Comment by blackholeearth** [comment]
last one should have worked..  
1 run it 
2 move slider.  (if you dont move slider it wont work/save.)
then suspend resume..

if you exit app i doesnt work.

**Comment by domusW** [comment]
1) I run it (it always runs, starts at startup, by the way);
2) I click it and it shows 53;
3) I move the slider to 100;
4) I switch off the monitor, then back on again;
5) I click it and it shows again 53.

I tested this several times, but I must admit that at ONE time, it DID switch back to 100. So it does occasionally work now.

**Comment by blackholeearth** [comment]
good to hear that.  

it doesnt save to disk.   so if app is killed. it cannot restore.

**Comment by domusW** [comment]
Good to hear that? It still doesn't work. I just wrote it seemed to work
once in the many times I tried. Just once.

I never ever kill the app.

But never mind.

**Comment by blackholeearth** [comment]
hah sorry.  that 100 value was the restored value??.  it worked Just once?? ok.
