### ISSUE TITLE
ManagementException: Not supported  on Win10 Ver 1709 Build 16299 64bit

### ISSUE THREAD

**Issue by K5jic** [blackholeearth/Win10_BrightnessSlider#5]
Same problem as mentioned in issue #3 - Microsoft.NET Framework - Unhandled exception has occurred in your application. I chose continue and an icon appeared in System Tray, but clicking on it causes app to terminate.

K5jic

**Comment by kaartman** [comment]
Hello, on my pc, same version, everything works.

**Comment by K5jic** [comment]
Kaartman,

Thanks for feedback. I have several PCs running Win10 (all running Ver 1709 Build 16299 64bit). I'll try it on one of those.

Dale....
^^^^^^^^

At 11:37 AM 12/10/2017, kaartman wrote:
>Date: Sun, 10 Dec 2017 17:37:53 +0000 (UTC)
>From: kaartman <notifications@github.com>
>To: blackholeearth/Win10_BrightnessSlider <Win10_BrightnessSlider@noreply.github.com>
>Cc: K5jic <k5jic@vivaldi.net>, 
> Author <author@noreply.github.com>
>Subject: Re: [blackholeearth/Win10_BrightnessSlider] Install fails in Win10
> Ver 1709 Build 16299 64bit (#5)
>
>Hello, on my pc, same version, everything works.

**Comment by kaartman** [comment]
On a pc windows 10 home x64 (1709_16299.125), the tweak does not work. 

************** Texte de l'exception **************
System.Management.ManagementException: Non pris en charge 
   à System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   à System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   à Win10_BrightnessSlider.Form1.GetBrightness()
   à Win10_BrightnessSlider.Form1.UpdateStatesOnGuiControls()
   à Win10_BrightnessSlider.Form1.Form1_Load(Object sender, EventArgs e)
   à System.Windows.Forms.Form.OnLoad(EventArgs e)
   à System.Windows.Forms.Form.OnCreateControl()
   à System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   à System.Windows.Forms.Control.CreateControl()
   à System.Windows.Forms.Control.WmShowWindow(Message& m)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   à System.Windows.Forms.Form.WmShowWindow(Message& m)
   à System.Windows.Forms.Form.WndProc(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Assemblys chargés **************
mscorlib
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.2600.0 built by: NET471REL1LAST
    CodeBase : file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Win10_BrightnessSlider
    Version de l'assembly : 1.0.1.0
    Version Win32 : 1.0.1.0
    CodeBase : file:///C:/Users/chant_000/Desktop/Win10_BrightnessSlider.exe
----------------------------------------
System.Windows.Forms
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.2556.0 built by: NET471REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.2556.0 built by: NET471REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.2556.0 built by: NET471REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.2556.0 built by: NET471REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.2600.0 built by: NET471REL1LAST
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.2556.0 built by: NET471REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Management
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.2556.0 built by: NET471REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Windows.Forms.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.2556.0 built by: NET471REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
mscorlib.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.2556.0 built by: NET471REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

**Comment by blackholeearth** [comment]
check the answer at that post.  
https://github.com/blackholeearth/Win10_BrightnessSlider/issues/3

**Comment by blackholeearth** [comment]
v1.2 released try that please.
