### ISSUE TITLE
formatexception parseuint32 at culture: german

### ISSUE THREAD

**Issue by moritzwa** [blackholeearth/Win10_BrightnessSlider#50]
Every time after using the slider for one of my external monitors (see Setup) I get this error:

![Capture](https://user-images.githubusercontent.com/42035131/62033762-fb6af600-b1ec-11e9-9e4f-768f48769d19.PNG)

Here the full description:

> 
> Informationen über das Aufrufen von JIT-Debuggen
> anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.
> 
> ************** Ausnahmetext **************
> System.FormatException: Die Eingabezeichenfolge hat das falsche Format.
>    bei System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
>    bei System.Number.ParseUInt32(String value, NumberStyles options, NumberFormatInfo numfmt)
>    bei System.UInt32.Parse(String s)
>    bei Win10_BrightnessSlider.DxvaMonFn.SetPhysicalMonitorBrightness(PHYSICAL_MONITOR physicalMonitor, Double brightness)
>    bei Win10_BrightnessSlider.RichInfoScreen.SetBrightness(Int32 value, Boolean _isMouseDown)
>    bei Win10_BrightnessSlider.uc_brSlider.trackBar1_Scroll(Object sender, EventArgs e)
>    bei Win10_BrightnessSlider.uc_brSlider.TrackBar1_MouseUp(Object sender, MouseEventArgs e)
>    bei System.Windows.Forms.Control.OnMouseUp(MouseEventArgs e)
>    bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    bei System.Windows.Forms.Control.WndProc(Message& m)
>    bei System.Windows.Forms.TrackBar.WndProc(Message& m)
>    bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Geladene Assemblys **************
> mscorlib
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.7.3416.0 built by: NET472REL1LAST_B.
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll.
> ----------------------------------------
> Win10_BrightnessSlider
>     Assembly-Version: 1.0.1.0.
>     Win32-Version: 1.0.1.0.
> 

My setup consists out of these Monitors:

![Unbenannt](https://user-images.githubusercontent.com/42035131/62034305-1427db80-b1ee-11e9-82bb-541357118b64.PNG)

The second one in the one which causes the error.

**Comment by blackholeearth** [comment]
some  monitors doesnt work.

**Comment by blackholeearth** [comment]
ok i think i  found the problem  your screen is german culture.  

i will give you beta version if it works on you . i will make it as public version

will put url here in 5 min
