### ISSUE TITLE
 unable to control  brightness since Win10 update 1903  on ASUS and HP laptop

### ISSUE THREAD

**Issue by jefken153** [blackholeearth/Win10_BrightnessSlider#51]
Since Windows 10 update 1903 I have been unable to control the brightness of my screen on my Asus and HP laptops , I have installed blackholeearth / Win10_BrightnessSlider on both of my laptops. The installation was successful and I see the brightness control in my systray. I can shift that from 0% to 100%. Unfortunately, this gives no result and there is no control of the light intensity.
Is this suitable for the screens of a laptop?

**Comment by blackholeearth** [comment]
yes . i made this for my laptop first. 

update mess up the  driver. 
 thats why disable  win update & auto driver updates.
i use  o&o shutupwin10 to do this.  

you have to get to previous driver. if driver messed up nothing i can do .

**Comment by blackholeearth** [comment]
please try to update your driver with the app thats is described here.

https://github.com/blackholeearth/Win10_BrightnessSlider/issues/32#issuecomment-436633507

**Comment by blackholeearth** [comment]
problem solved
bad drivers on monitor in apparaatbeheer
after deleted the drivers problem was solved

_Originally posted by @jefken153 in https://github.com/blackholeearth/Win10_BrightnessSlider/issues/32#issuecomment-527425488_
