### ISSUE TITLE
v1.7.9 shows up as Trojan:Win32/Casdet!rfn

### ISSUE THREAD

**Issue by danarnold** [blackholeearth/Win10_BrightnessSlider#55]
Windows Defender blocks v1.7.9, claiming it contains [Trojan:Win32/Casdet!rfn](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:Win32/Casdet!rfn&threatId=-2147239784).

**Comment by blackholeearth** [comment]
read , readme
