### ISSUE TITLE
Windows Defender identifies program as a trojan

### ISSUE THREAD

**Issue by ka15574** [blackholeearth/Win10_BrightnessSlider#57]
![Trojan](https://user-images.githubusercontent.com/35844928/70392534-17f31800-19af-11ea-9527-589f384dea40.PNG)

**Comment by blackholeearth** [comment]
add app to white list  of your antivirus .  read the readme? if you dont trust, dont use.

**Comment by blackholeearth** [comment]
for  v1.7.9 .  windows defender submit result:

                We have removed the detection.  Please follow the steps below to clear cached detection and obtain the latest malware definitions.

     1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
     2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
     3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

**Comment by wooseopkim** [comment]
@blackholeearth The same still happens with BitDefender. I can't even download the exe file because BitDefender thinks this is a malware.

**Comment by blackholeearth** [comment]
White list brightness. exe in you antivirus . Or delete antivirus.

**Comment by wooseopkim** [comment]
1. I already whitelisted it.
2. Delete AV? You serious?

**Comment by IsaaXuc3m** [comment]
I found very shady that you ask people to disable his AV to use you program. Also, not only Windows defender, Malwarebytes and Bitdefender also detect this as a trojan

**Comment by blackholeearth** [comment]
@isaa if you dont trust it. Dont use it. İ dont force any one to use it. İts my hobby app.

**Comment by VarunAgw** [comment]
Add Avast to the list. Maybe you can look into fixing the issue some day.

**Comment by blackholeearth** [comment]
Linking Issue about malwarebytes:  #79 

I couldn't view the forum. But they somehow unflagged .

**Comment by blackholeearth** [comment]
v1.7.10   windows defender false postive submission.       if you have virus alert  from windows defender , follow these steps.

Analyst comments:

We have removed the detection.  Please follow the steps below to clear cached detection and obtain the latest malware definitions.

     1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
     2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
     3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

Thank you for contacting Microsoft.

**Comment by trillwin** [comment]
use virustotal, its better
