### ISSUE TITLE
Brightness on second that was set with slider changes back as soon as I click inside second monitor

### ISSUE THREAD

**Issue by welle89** [blackholeearth/Win10_BrightnessSlider#58]
Hi, 
I have two monitors.
The first one I set the brightness and then start clicking inside it, the brightness stays as I set it with BrightnessSlider. For the second monitor, I set the brightness with BrightnessSlider slider. 
But when I click inside second monitor, the brightness instantly reverts back to the brightness that was before.
It's like as if my click inside the second monitor overwrites the setting that brightness slider did before hand. But it's only for the second monitor.

Thank you

**Comment by blackholeearth** [comment]
1. make sure full performance (not power saving)
Power plan> mode> full performance

2. After selecting full perormance.
  Full performance> plan details > Disable adaptive brightness

Nvida, intel has adaptive brigtness inside their controlpanel i have read before. Make sure they arer disabled.

There are tutorials on Google how to disable adaptive brigthness

**Comment by blackholeearth** [comment]
this might be related to #49 .

**Comment by blackholeearth** [comment]
here 7.13 test . 
[Win10_BrightnessSlider.zip](https://github.com/blackholeearth/Win10_BrightnessSlider/files/6663144/Win10_BrightnessSlider.zip)


try this.??
i added savemonitorsetting.  its only appicable dxva(external plugged cable monitors).
