### ISSUE TITLE
Not supported.

### ISSUE THREAD

**Issue by Beyarz** [blackholeearth/Win10_BrightnessSlider#6]
When I open the application I get this error:

System.Management.ManagementException: Not supported 
   vid System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   vid System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   vid Win10_BrightnessSlider.Form1.SetBrightness(Byte targetBrightness)
   vid Win10_BrightnessSlider.Form1.trackBar1_Scroll(Object sender, EventArgs e)
   vid System.Windows.Forms.TrackBar.OnScroll(EventArgs e)
   vid System.Windows.Forms.TrackBar.WndProc(Message& m)
   vid System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   vid System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   vid System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

  
System.Management
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll

**Comment by blackholeearth** [comment]
check the answer at that post.
#3

**Comment by blackholeearth** [comment]
v 1.02 is released. it support ddc/ci via dxva2 . that means if your monitor supports "ddc/ci", and it is ENABLED in the monitor settings.
you can try your luck.

**Comment by blackholeearth** [comment]
v1.2 released try that please.
