### ISSUE TITLE
Rookie here, How the heck do I run this program? 

### ISSUE THREAD

**Issue by Spiderlock** [blackholeearth/Win10_BrightnessSlider#61]
I cannot figure out how to run this program.  I have downloaded it, there are no visible executable installers in the file.  I then downloaded Github desktop and there was nothing to help me there either.  Can someone enlighten me?

**Comment by RolandMisica** [comment]
Open this link: https://github.com/blackholeearth/Win10_BrightnessSlider/releases and you will see list of all releases (versions) and their corresponding executables
