### ISSUE TITLE
Default level set to 23

### ISSUE THREAD

**Issue by Shine753** [blackholeearth/Win10_BrightnessSlider#63]
Hi,
Tested on 2 Windows 10 x64 and 7 machines, on a calibrated monitor. 
The slider starts at 23.

**Comment by Shine753** [comment]
Why just... closed ?

**Comment by blackholeearth** [comment]
You just made statement. 
What is your problem???   

İts about your computer.  Not caused by this app.   Try disabling adaptive brighness.

İf you cant change the brighness.

**Comment by Shine753** [comment]
Well, ok, after some tests, I think I understand the way Win10_BrightnessSlider works : it shows and change the monitor brightness setting. But it don't use it as a starting 100% value as other softs do to adjust it then on the fly into Windows from 100% to 0% without affecting the monitor setting itself.
