### ISSUE TITLE
System.InvalidOperationException: Nullable object must have a value.

### ISSUE THREAD

**Issue by gezawatt** [blackholeearth/Win10_BrightnessSlider#64]
When I have one of my displays turned off via nvidia control panel, the program still sees it as a display, on which I can change brightness. If I try to change it, it gives me an "System.InvalidOperationException: Nullable object must have a value." exception. 
![Screenshot_3](https://user-images.githubusercontent.com/62294693/76863632-d3f69580-6870-11ea-9805-abf53dd2a7de.png)
[exception.txt](https://github.com/blackholeearth/Win10_BrightnessSlider/files/4343784/exception.txt)

**Comment by blackholeearth** [comment]
Closely Related  to #35  . 

 not a critical problem.
