### ISSUE TITLE
Enhancement : Adjust brightness relative to current monitor brightness

### ISSUE THREAD

**Issue by Shine753** [blackholeearth/Win10_BrightnessSlider#65]
As far as i can see, the app adjusts the hardware setting of the monitor brightness. 
So when switching, using a switch, from a basic computer where the app is installed to another that is color calibrated, you loose your color calibration.

So it would be great to be able to choose beetween the existing behaviour, and another new one that would adjust the brightness from 100% to 0% based on the existing hardware brightness set for the screen, so the brightness change only affects the computer on which the app is installed.

**Comment by blackholeearth** [comment]
İm sorry but i dont understand anything? 
Pc1 -- plugged -- monitor1
Pc2 -- 
Do you mean  you change brighness on pc1.
 then  connect pc2 to  Mon1 ???
And loose  brigness level.?

İ dont know how to do that.  monitor 1 has to remember it?? 
İts too much luxurious thing. İ dont kbow that is even possible??

**Comment by Shine753** [comment]
I mean :
1 have 2 PC, 1 screen, 1mouse, 1 keyboard.
I switch from one PC to the other using the switch.
PC1 is a "stanndard" PC with Win10_BrightnessSlider installed.
PC2 is a color calibrated PC without Win10_BrightnessSlider.
Let's say that the monitor has its hard brightess setting set to 50.

When I open Win10_BrightnessSlider on PC1, I can see the level set to 50, and can adjust it, for example at 40. But this changes the monitor setting and set it to 40.
So when I switch to PC2, my color calibration is not good anymore.

I expect a behaviour that can allow Win10_BrightnessSlider start to 100, or 50 if you prefer. And let me adjust the brightness on PC2 without affecting the monitor setting. Then if I switch to PC2, the color calibration in still good as the monitor is still set at 50.

For example, this is the way Desktop Lighter 1.4 works.
