### ISSUE TITLE
Didn't work when connect/disconnect monitor

### ISSUE THREAD

**Issue by mtrakal** [blackholeearth/Win10_BrightnessSlider#68]
It did not detect changes when connect/disconnect monitor.

It should be super easy to use events handler to recognize when monitor is connected/disconnected. 
Have connected monitor, disconnect cable, after connect again. Slider didn't work.
When you just disconnect, you have 2 sliders and not just one.
When you just connect monitor, you have still just one slider, not 2.

**Comment by blackholeearth** [comment]
After every physical operation. 
Right click on the sun icon in tray
 press detect  monitor (it scans again.)

İts written in the read me!!

**Comment by blackholeearth** [comment]
try new version v1.7.11
monitor on off
monitor plug unplug
system suspend resume events are added
