### ISSUE TITLE
It does not work!

### ISSUE THREAD

**Issue by borsn** [blackholeearth/Win10_BrightnessSlider#7]
I tried it on Windows 10 Home. Windows 10 Pro and nothing...

Can you fix it?

**Comment by blackholeearth** [comment]
$monitor = Get-WmiObject -ns root/wmi -class wmiMonitorBrightNessMethods$monitor.WmiSetBrightness(80,10)

 pas this code on windows powershell if this doesnt work. then there is nothing i can do. cuz my app uses that code internally.  
some monitors doesnt provide wmi api for their hardware . if they dont provide it. there is nothing i can do.

**Comment by blackholeearth** [comment]
ManagementException: Not supported on Insider Preview Build 17046 #3

**Comment by blackholeearth** [comment]
https://github.com/blackholeearth/Win10_BrightnessSlider/issues/3

**Comment by blackholeearth** [comment]
v 1.02 is released. it support ddc/ci via dxva2 . that means if your monitor supports "ddc/ci", and it is ENABLED in the monitor settings.
you can try your luck.
