### ISSUE TITLE
Enabling brightness hotkeys for second display.

### ISSUE THREAD

**Issue by pbakes** [blackholeearth/Win10_BrightnessSlider#70]
Brightness hotkeys would make a great addition to this software. This software is great for pairing my ThinkPad P52 with the LG 24MD4KL-B 4K UltraFine display.

**Comment by tsonkov** [comment]
Basically works perfect for all the brands with unstable utility softwares or buggy drivers. Mine is Gigabyte Aero 15x and I cant stand the bloat that the manufacturer has put in it...

Besides that - perfect job, man, lova the app! 👍

**Comment by nomco** [comment]
I also very much hope to increase the hotkey function.

**Comment by pbakes** [comment]
Try the Windows Store app Twinkle Tray. I switched to that, its got a little more functionality, including hotkeys.

**Comment by blackholeearth** [comment]
#4
