### ISSUE TITLE
Sliders always appear on bottom right of primary monitor

### ISSUE THREAD

**Issue by Nu11u5** [blackholeearth/Win10_BrightnessSlider#71]
### Issue:

The brightness sliders always appear on the bottom right corner of the primary monitor, regardless of where the system tray is located.  Windows allows the system tray to be moved via the taskbar to any edge of the screen, even to another monitor.

If I move the taskbar/system tray to a secondary monitor, the brightness sliders still appear in the bottom right corner of the primary monitor.

### Expected behavior:

The brightness sliders should always appear adjacent to the system tray, even when it has been re-positioned by moving the taskbar.  This includes when the taskbar is moved to a side or top edge, and/or moved to a secondary monitor.

**Comment by blackholeearth** [comment]
try v1.7.11  . is it still problematic.

**Comment by Nu11u5** [comment]
> 1. try latest verison,  v1.7.11  . does issue still exist ?

Yes, the issue still exists on v1.7.11.

> 2. how many monitors you have ?

I use two monitors connected to a desktop computer.

> 3. which mode you use ??. (press Win+P)

The monitors are configured as "extend".

---

The sliders will follow the system tray but only on the primary display (the one marked "make this my main display" in display settings).  When the task bar is moved to a different monitor than the primary the sliders only appear in the bottom right corner of the primary display.

**Comment by blackholeearth** [comment]
try this  version.

[Win10_BrightnessSlider.zip](https://github.com/blackholeearth/Win10_BrightnessSlider/files/6661356/Win10_BrightnessSlider.zip)
