### ISSUE TITLE
Taskbar icon does not display in tablet mode

### ISSUE THREAD

**Issue by julianabaez** [blackholeearth/Win10_BrightnessSlider#72]
I have the Taskbar icon running on my 2 in 1 laptop in laptop mode. When i boot up to or switch to tablet mode, the icon disappears in the Taskbar. When I switch back to laptop mode it reappears in the Taskbar. 

This Is true regardless of how I have the tablet/laptop oriented.  

Edit: This is on windows 10

**Comment by blackholeearth** [comment]
this is controlled by windows 10 . no app can bypass it.
