### ISSUE TITLE
Error "Form1" when starting app

### ISSUE THREAD

**Issue by gradation** [blackholeearth/Win10_BrightnessSlider#75]
Hello, I'd really love to use this app. I see from the photos it has a great interface and very simple to use. However, when start the app I get an error that says 

"Form1: Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately. Nullable object must have a value."

 Is this something that can be fixed?

Details:
    Assembly Version: 4.0.0.0
    CodeBase:  etc.dll
"""""
(these dll files doesn't give me any info . So i trimmed. )

**Comment by blackholeearth** [comment]
This is totally useless.  
"Nullable object must be true."
If there were a stacktrace. Which function has caused this
