### ISSUE TITLE
-1 brightness and no effect on the slider on 1 of 3 displays

### ISSUE THREAD

**Issue by sum5l** [blackholeearth/Win10_BrightnessSlider#76]
![image](https://user-images.githubusercontent.com/71645383/93766029-18932d00-fc16-11ea-9878-5894cfe63370.png)

3 displays, 
No. 1 - BenQ EW3270U, DisplayPort
No. 2 - HP LP2465, DVI/DisplayPort (adapter)
No. 3 - HP LP2465, DVI

The problem occurs only with No. 2. Unplugging, detecting, rebooting doesnt help. Maybe an issue with using an DVI/DP adapter?

**Comment by Juno72** [comment]
If you know Python you can try:
https://github.com/Juno72/MonitorControl

**Comment by blackholeearth** [comment]
Try emoacht monitarian . In github.

**Comment by blackholeearth** [comment]
https://github.com/xanderfrangos/twinkle-tray/wiki/Display-Detection-&-Support-Issues#common-reasons-for-monitors-not-being-supported-or-detected

6.) 
Incompatable hardware - Some hub and converters may strip DDC/CI functionality. If possible, test these monitors without the hubs and/or converters to see if they're causing the issue.
