### ISSUE TITLE
Lack of a usable way to encourage you

### ISSUE THREAD

**Issue by AIceste** [blackholeearth/Win10_BrightnessSlider#77]
Hi,

Despite being quite simple, this software has truly been a life saver for me. Of course, some small features are sometime lacking (some of which are already listed in other issues, namely #4 *cough*), and I sometime find myself wishing there was a (working) alternative to manually handle both screen brightness and color temp with a single app, but all in all, this is the good stuff, y'know?

I think stuff like that needs to be encouraged somehow, and I was wondering if there was any linear, less-than-7-steps way to do just that from my computer.

**Comment by blackholeearth** [comment]
There was a similar issue for master brightness slider to change all screen brightness.
