### ISSUE TITLE
Icon disappears from taskbar

### ISSUE THREAD

**Issue by josvanr** [blackholeearth/Win10_BrightnessSlider#80]
hello

I've been trying your app. It works but the icon in the taskbar disappears after a while. Then I have to restart the app again, and the icon appears again. Then after doing this a couple of times, the icon doesn't appear anymore in the taskbar, aslo after starting the app, also when starting the app a couple of times. Then after some time (5 minutes?) if I start the app again, the icon does appear in the taskbar again. (and disappears after a couple of minutes.)

I have windows 10.0.18363 and my taskbar is on top, with authide enabled......

**Comment by blackholeearth** [comment]
A) U have some app that it kills it. ?? Antivirus?? Idk

B) U know,  in system tray , icons hide theirselves in there. u have to drag it out near to the wifi/sound icon.
