### ISSUE TITLE
Cannot set brightness after resuming from suspend

### ISSUE THREAD

**Issue by dawcal** [blackholeearth/Win10_BrightnessSlider#83]
I like the utility, but I've one problem.

Windows 10, Thinkpad X1 G6. Three monitors (one internal, two external).
After resuming from suspend, I cannot set any brightness on one external monitor (LG 27UK600-W).
The brightness application shows brightness "-1". Moving the slider doesn't bring any changes in the brightness of the monitor.

The LG monitor is connected by USB-C to DisplayPort cable.

Using the "Detect Monitors" options resolves the issue, until the next suspend-resume cycle.

**Comment by blackholeearth** [comment]
try v1.7.11  i added resume suspend

**Comment by dawcal** [comment]
Thank you. I'm using 1.7.11 now.

**Comment by blackholeearth** [comment]
is it working ?? suspend resume ??

**Comment by dawcal** [comment]
I just tried suspend and then resume. It seems to be working fine - slider shows the current brightness settings and moving the sliders changes the brightness.

Thank you for your work!
