### ISSUE TITLE
Request : auto detect monitor

### ISSUE THREAD

**Issue by jaylay99** [blackholeearth/Win10_BrightnessSlider#84]
I'm pretty sure I'm not the only one to have a monitor that has different presets and everytime I switch preset I got to click on ''detect monitor'' to make the slider work again, it'd be great to have an ''auto detect" option when you left click on the Win10_BrightnessSlider tray icon. 

Other than that, the UI, simplicity and the app is 10/10, keep up the good work!

**Comment by blackholeearth** [comment]
1) What dou you mean "presets" ?  

2) When does your slider stops. and  you need to press the deck monitor again ?

**Comment by patryk-siewiera** [comment]
I could confirm this also LG 27” 27UL850-W; always before changing brightness I need to click "Detect monitors"

ps. lovely app!

**Comment by blackholeearth** [comment]
try v1.7.11   i put  monitor on off , plug unplug detection. does it work ?????

**Comment by jaylay99** [comment]
Thank you for your reply. I wanted to confirm that yes the new version fixed this! No issues whatsoever. Thank you very much.
