### ISSUE TITLE
Exe removed from package?

### ISSUE THREAD

**Issue by thetroublemaker** [blackholeearth/Win10_BrightnessSlider#89]
Has the executable been removed from the package? I downloaded the package and see the c# project file but no exe.

**Comment by blackholeearth** [comment]
Yes

**Comment by thetroublemaker** [comment]
Why?

**Comment by blackholeearth** [comment]
As written in the main page. Code published in github is v1.01

 v1.79  v1.4  have exe but their source code wont be released.
