### ISSUE TITLE
pop up taskbar blocks slider window

### ISSUE THREAD

**Issue by chupame** [blackholeearth/Win10_BrightnessSlider#9]
my taskbar  is set to auto hide.
when I click on the notifyicon1 (the little sun) then it pops up below the raised taskbar.
i need to move the mouse up a bit so the taskbar hides again to gain access to the slider.
is this done on purpose?
thank you for helping us poor win10 buggers out and fix one of the many "improvements" of 10.
i also second the thing with the hotkeys
i used volbright first but punching twice on the win key (with all the pop ups) and then fn and volume control is a bit like driving a very old car without syncronisation.

**Comment by blackholeearth** [comment]
now it will popup over the taskbar, but  will be right above the taskbar.. thats all i can do right now.
------
slightly fixed.

**Comment by chupame** [comment]
Thank you works like a charm now *****

**Comment by blackholeearth** [comment]
really thank you for feed back.  can you  open slider window and come over to  sun icon. it  shoud show tooltip  what does it says ??   
 
a) "WMI, FallBack to Dxva"  
b) "dxva" 
c) "WMI"

**Comment by chupame** [comment]
the updated program reads "WMI, FallBack to Dxva"

the tooltip from the sun in the taskbar reads notifyicon1

maybe a better matching name could be inserted with the next update

like brightness slider or brighslide or short BS ;)

tested with win 8.1 and 10 1703

greetings from Spain

**Comment by blackholeearth** [comment]
thank you. for feedback.
