### ISSUE TITLE
Change the brightness when you just click in the bar

### ISSUE THREAD

**Issue by kkkmilo** [blackholeearth/Win10_BrightnessSlider#94]
Hi, it would be awesome if you could **change the brightness when you just click in the bar**, besides drag the simbol in the bar, i tried but i have to press a few times to reach from one side to another, change it with the mouse scroll would be nice too (someone already said that)

**Comment by blackholeearth** [comment]
nice explanation.  

jump trackbar value to click.    experimental.   

i only tested with 
a) 96 dpi  100%  
b) ?? dpi  125% (in windows settings)

there was not a clean solution  clicked postion was out of sync at least 5pts. i fixed it for the  96 and and 96*(125%) dpi
