### ISSUE TITLE
Recent Update blocked by Windows Defender

### ISSUE THREAD

**Issue by thetroublemaker** [blackholeearth/Win10_BrightnessSlider#96]
Defender claims that the package contains: Trojan:MSIL/AgentTesla.OXHB!MTB

**Comment by TarasMykytka** [comment]
I've got today "Trojan:Win32/Emali.A!cl" but I'm using latest version for 2 days. 
Looks like false-positive result. I've add it to exeptions.

**Comment by blackholeearth** [comment]
submitted  to https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by blackholeearth** [comment]
win10_brightnessslider - v17.11.exe

Analyst comments:
                We have removed the detection.  Please follow the steps below to clear cached detection and obtain the latest malware definitions.

     1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
     2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
     3. Run "MpCmdRun.exe -SignatureUpdate"
