### ISSUE TITLE
1.7.11 - Events problem

### ISSUE THREAD

**Issue by Onepamopa** [blackholeearth/Win10_BrightnessSlider#97]
I have 3 monitors, one is a TV, so, unable to change the brightness (which is OK, it passes via hdmi receiver anyway)
The other two are identical monitors (AOC).

Both set to 100% brightness, however, after power off/on one of them, sometimes the values appear as 000 instead of 100% after the icon is clicked.

Other than that - everything seems to be fine.

**Comment by blackholeearth** [comment]
what is the log ? paste here.  rightclick > show log

**Comment by Onepamopa** [comment]
This only happened once, I wasn't able to reproduce it (yet).
If I do - I'll check the log.

**Comment by Onepamopa** [comment]
By the way, on the previous version... rasman.dll was used (referenced), which is very suspicious...
I'm glad to see it's not on the current version.

**Comment by blackholeearth** [comment]
about dlls .  i didint change any ref  

about 000: i found the reason.  i didnt call update gui.  try this. if no error ill push this.

[Win10_BrightnessSlider.zip](https://github.com/blackholeearth/Win10_BrightnessSlider/files/6676953/Win10_BrightnessSlider.zip)

**Comment by Onepamopa** [comment]
I will check it later, right now... other work.

**Comment by Onepamopa** [comment]
v1.7.14 - 000 still appears from time to time after stop/start of a monitor, but then "resets" to the previous values within 1 second.

Suggestions:
- When a monitor does not support brightness adjustment (Initially detected value is -1) - simply hide it from the list, and log a message.
- When a monitor is suspended or turned off - make the slider non-adjustable, and return it to normal state when the monitor appears again.
- When you click on the W10BS icon - the menu appears and disappears "directly" -- Make it using some sort of "easing" like when you click on the keyboard input switch icon, or like EarTrumpet - appearing from top to bottom -- looks great that way.

**Comment by blackholeearth** [comment]
yes i put 1 second delay  to make screen be ready for scan. sometimes they might respond late. 
its expected bahaviour.

**Comment by Onepamopa** [comment]
Check the suggestions too :)
