### ISSUE TITLE
Source

### ISSUE THREAD

**Issue by Onepamopa** [blackholeearth/Win10_BrightnessSlider#98]
I don't know why you don't just place the updated source code in github and make an appropriate license.
Considering (almost) everyone can disassemble the binary, export it as a new VS project and compile it from source....

People get suspicious when someone distributes just a binary w/o the actual code.

Don't get me wrong, you're doing an awesome job. I'm using your software in Windows VMs that I use on my PC (Proxmox host, 3 windows VMs with 3 GPUs pass-through, so each has a dedicated GPU and monitor), but Microsoft's brightness adjustment in the notification bar is missing (since this is not a Laptop, for example).. so the only way for me to change brightness in this scenario is to use your soft.

In any case, this is up to you and I respect that.

**Comment by Suisse00** [comment]
If somebody is looking for code source I found https://github.com/castro12321/SlimShady .

It seems to use WMI, DDC (which is the only way that work on my end) or even add a software luminosity.
